---
title: "Talks and Workshops"
format: html
---

Here is a list of the talks and workshops I have given in the last 5 years:

#### 2025

- **Timbers, T.** (2025). Prompting the Professoriate: A Qualitative Study of Instructor Perspectives on LLMs in Data Science Education. *Math Faculty Teaching Seminar, University of Waterloo* (Virtual) Local
- **Timbers, T.**, Burak, K. (2025). Introduction to machine learning in Python with 
Scikit-learn. *posit::conf* (Atlanta, GA) International
- **Timbers, T.** (2025). Designing and delivering data science programs for different audiences. Statistical Society of Canada Annual Meeting (Saskatoon, SK) National

#### 2024

- **Timbers, T**, Chen, D. (2024). Introduction to machine learning in Python with 
Scikit-learn. *posit::conf* (Seattle, WA) International
- **Timbers, T.** (2024). Societal Pressures for Trustworthy Data Analysis. *Joint 
Statistical Meeting* (JSM) (Toronto, ON) International
- Burak, K., Chen, D., Rodriguez-Arelis, A., **Timbers, T.** (2024). How to create and 
distribute R packages (workshop). *Statistical Society of Canada Annual Meeting* 
(St. John’s, NL) National
- **Timbers, T.**, Campbell, T. (2024). Reflections on scaling an Introduction to Data 
Science. *Statistical Society of Canada Annual Meeting* (St. John’s, NL) National

#### 2023

- **Timbers, T.** (2023). 10 simple rules for teaching Data Science. International Day 
of Women in Statistics and Data Science 2023 (Virtual Conference) International
- **Timbers, T.** (2023). Opinionated practices for teaching reproducibility: 
motivation, guided instruction, and practice. Joint Statistical Meeting (JSM) 
(Toronto, ON) International

#### 2022

- **Timbers, T.** (2022). 10 simple rules for teaching R for Data Science (Keynote). 
*Cascadia R Conference* (Virtual Conference) Local
- **Timbers, T.** (2022). Reproducibility: you can do data analysis without it, but 
should you? *Joint Statistical Meeting* (JSM) (Washington, DC, USA) International
- Campbell, T., Lee, M., **Timbers, T.** (2022). Creating Open Resources for an 
Introductory Data Science Course. *Statistical Society of Canada Annual Meeting* 
(Virtual Conference) National
Burr, W., **Timbers, T.** (2022). Reproducibility Workshop. *Statistical Society of 
Canada Annual Meeting* (Virtual Conference) National 

#### 2021

- **Timbers, T.** (2021). Opinionated practices for teaching reproducibility: 
motivation, guided instruction and practice. *Canadian Statistical Sciences Institute 
(CANSSI) Ontario / University of Toronto Statistical Sciences Data Science Applied 
Research and Education Seminar* (ARES) (remote hosted in Toronto) Local
- **Timbers, T.** (2021). Opinionated practices for teaching reproducibility: 
motivation, guided instruction and practice. *Centre de recherches mathématiques –
Université de Montréal statistics colloquium series* (remote hosted in Montreal) 
Local
- **Timbers, T.** (2021). Teaching Data Science Authentically Using Open Source
Educational Resources. *Joint Statistical Meeting* (JSM) (Virtual Conference) 
International
- **Timbers, T.** (2021). Automated feedback with Jupyter, nbgrader and R. 
Statistical Education Workshop on Open Source Solutions for Online Teaching, 
Assessment and Grading. *Statistical Society of Canada Annual Meeting* (remote 
hosted in Canada) National
- **Timbers, T.** (2021). Introduction to reticulate. *R Ladies Tunis* (remote hosted in Tunis, Tunisia) Local
- **Timbers, T.** (2021). Programming with tidyverse functions. *R Ladies Vancouver* 
(remote hosted in Vancouver, BC) Local
- **Timbers, T.** (2021). Teaching reproducibility: motivation, direct instruction and 
practice. *Toronto Data Workshop on Reproducibility, University of Toronto*. (remote 
hosted in Toronto) Local
